export const LIST_AUTHORS = 'AUTHORS/LIST_AUTHORS';
export const ADD_AUTHOR = 'AUTHORS/ADD_AUTHORS';
export const UPDATE_AUTHORS = 'AUTHORS/UPDATE_AUTHORS';
export const DELETE_AUTHORS = 'AUTHORS/DELETE_AUTHORS';
